# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 127d56ac3116ef523ade4c6d1523471d4b9832c64da13eb1e90ec62b3b175e2c5711cd1051237dd7088d8bd9791194f40e15d3908495d5f97d029d6f38933751

test:
  secret_key_base: 16c5ae6ad5bc174171d40f463dce73f857ffb7367449bafedc49603ef5540ff865c0bd0383116bc8ee17c484c7080f994e3237e9022f6b56f14f2f91f6f4d5a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
